### PR TITLE
Rename "Designer" targets -> "DesignTime" targets

### PR DESCRIPTION
**Pull request by davkean**
This is to mirror C++ which has a similar concept.

### CODE REVIEW

**Comment by davkean** [comment]
tag @dotnet/roslyn-analysis

**Comment by jinujoseph** [comment]
:+1:

**Comment by basoundr** [comment]
The content itself is related to the AppDesigner. Wouldn't `DesignTime` convey a different meaning to the Targets?

**Comment by davkean** [comment]
@basoundr There are intentions that all design-time goo goes in here. There's only AppDesigner because that's only thing that we've implemented.

**Comment by basoundr** [comment]
sounds good then :+1:

**Pull request merged**
