### PR TITLE
Change the persistence of the Version of the Package Reference to be …

### PR DESCRIPTION
**Pull request by basoundr**
…an Attribute

With this change, the Version of a packagereference will be added as a Attribute rather than a Metadata.

This will help us in having smaller project files with less space and less lines for Package references.

We need change from CPS and Msbuild to make this works. The CPS changes are already in the WPT branch and the msbuild changes to fix a vital bug is almost there(waiting to be merged) in WPT.

@srivatsn @dotnet/project-system for review

### CODE REVIEW

**Comment by srivatsn** [comment]
Have you verified that with Jacob's recent CPS and project system PRs this scenario works?

**Comment by basoundr** [comment]
Just the CPS change wont be enough. We will still need the msbuild change. Without which VS will still crash

**Comment by srivatsn** [comment]
With #726 we shouldn't crash anymore and we should just get a dialog to reload the project even without the msbuild change.

**Comment by basoundr** [comment]
@srivatsn verified with the CPS binaries and this change and we persist the Version as Attribute as expected instead of Metadata

**Comment by basoundr** [comment]
@dotnet-bot retest please

**Comment by srivatsn** [comment]
The error seems to be:

```
14:58:11 ProjectSystem\Rules\PackageReference.xaml : error : XamlObjectWriterException: Cannot set unknown member 'Microsoft.Build.Framework.XamlTypes.DataSource.PersistenceStyle'. [D:\j\workspace\windows_debug---65a0f312
```

I suspect we need a new NuGet package for CPS that understands the new property

**Comment by basoundr** [comment]
Jenkins reporting this error.

> 14:58:27 ProjectSystem\Rules\PackageReference.xaml : error : XamlObjectWriterException: Cannot set unknown member 'Microsoft.Build.Framework.XamlTypes.DataSource.PersistenceStyle'. [D:\j\workspace\windows_relea---c9724ea3\src\Microsoft.VisualStudio.ProjectSystem.Managed\Microsoft.VisualStudio.ProjectSystem.Managed.csproj]
14:58:27 ProjectSystem\Rules\PackageReference.xaml : error :  [D:\j\workspace\windows_relea---c9724ea3\src\Microsoft.VisualStudio.ProjectSystem.Managed\Microsoft.VisualStudio.ProjectSystem.Managed.csproj]

Local build works just fine. Any idea?

**Comment by srivatsn** [comment]
Don't know why local build works but there is a task that generates cs files from the XAML and it looks like that task is blowing up saying it doesn't recognize this new property. So you need a new CPS package that comes with a new task to fix this

**Comment by basoundr** [comment]
@srivatsn Didnt refresh the page to see your previous comment. I have a dependency on the same CPS version in my local box and that builds. This could be a dependency on the newer msbuild.

**Comment by jviau** [comment]
The XAML classes are from MSBuild, not CPS.  Can you check what version of MSBuild you have on the build machine? https://github.com/Microsoft/msbuild/commit/3893df958c0ae24e02949739a70f8668699e4eb7

**Comment by srivatsn** [comment]
@dotnet-bot test this please

**Comment by srivatsn** [comment]
@dotnet-bot test this please

**Comment by basoundr** [comment]
Fixes #695

**Pull request merged**
