### PR TITLE
Update VB property pages to support portable and embedded debug info

### PR DESCRIPTION
**Pull request by tmat**

### CODE REVIEW

**Comment by tmat** [comment]
@davkean Where is the equivalent code for C#? Couldn't find it.

**Comment by davkean** [comment]
@tmat: When were these settings introduced?

@jasonmalinowski Any idea what happens when the old project system passed unrecognized options to the compiler? Say a WAP project with 1.0 compiler?

**Comment by tmat** [comment]
"portable" in Update 1, "embedded" here: https://github.com/dotnet/roslyn/pull/12711

**Comment by davkean** [comment]
@tmat It looks like you changed both the C# and VB one already.

**Comment by davkean** [comment]
@jinujoseph How are we representing the `DebugInfo` property? Do we list all of the available values in the rule

**Comment by tmat** [comment]
@davkean I see. It confused me that both lists are in VB code and completely different.

**Comment by tmat** [comment]
@davkean OK to merge?

**Comment by davkean** [comment]
@tmat Okay, I had concerns about csproj's behavior with old compiler bits - but I've convinced myself that's not a problem, as the in-memory compiler is always the latest.

:+1: 

As a side note how does embedded work? Are we changing the old project system to handle that case, for example, in the update-to-date case?

**Comment by tmat** [comment]
@davkean I was planning to update masbuild targets files and proj system as necessary. I'd appreciate any pointers to places that you know might need updating, so that I don't forget something.

**Comment by davkean** [comment]
@tmat Nowhere in particular, but I think that up-to-date checks might be broken by this.

**Pull request merged**
