### PR TITLE
Merge project system code

### PR DESCRIPTION
**Pull request by davkean**

### CODE REVIEW

**Comment by davkean** [comment]
tag @dotnet/roslyn-analysis 

This is the port of the project system from Roslyn.

**Comment by basoundr** [comment]
Even Codeflow can show only 64 commits :P

**Comment by davkean** [comment]
Apart from the last few commits, these are a straight port anyway.

**Comment by davkean** [comment]
test this please

**Comment by davkean** [comment]
test this please

**Comment by davkean** [comment]
test this please

**Pull request merged**
