### PR TITLE
Prefer CI machines with VS 15 Preview 3 from Preview 2

### PR DESCRIPTION
**Pull request by basoundr**
Tagging @tannergooding @dotnet/project-system for review

### CODE REVIEW

**Comment by basoundr** [comment]
test ci please

**Comment by davkean** [comment]
As per: https://github.com/dotnet/dotnet-ci/blob/79960fb78848c5803f39cd90ee03b729dff3e570/jobs/generation/Utilities.groovy#L168

**Comment by davkean** [comment]
This didn't test the CI.

**Comment by basoundr** [comment]
which is what I am wondering

**Comment by basoundr** [comment]
@dotnet-bot test ci please

**Comment by tannergooding** [comment]
The test phrase just creates the new jobs using the modified netci.groovy, it does not actually run the new jobs.

**Comment by tannergooding** [comment]
👍

**Pull request merged**
