### PR TITLE
Merge csc/vbc rules into a single rule

### PR DESCRIPTION
**Pull request by davkean**
Also merged common logic from DesignTime targets between C#/VB -> "Managed"

### CODE REVIEW

**Comment by davkean** [comment]
tag @dotnet/project-system

**Comment by davkean** [comment]
This simplifies the logic to call the rules - it only needs to listen to one rule, and it doesn't need language-specific components to provide more context such as what item to read or what language to pass to Roslyn.

**Comment by srivatsn** [comment]
:shipit:

**Comment by 333fred** [comment]
👍

**Pull request merged**
