### PR TITLE
Move the build version and Assembly Version from 15.0 to 15.3

### PR DESCRIPTION
**Pull request by basoundr**
@davkean @dotnet/project-system for review

### CODE REVIEW

**Comment by tannergooding** [comment]
@basoundr, shouldn't it be x.3.0 and not x.3.1?

**Comment by basoundr** [comment]
Thats true, we can downgrade that portion of the version

**Comment by davkean** [comment]
Can you do this change on top of https://github.com/dotnet/roslyn-project-system/pull/1738 or manually merge that change in master and throw away the changes? This isn't going to merge correctly.

**Comment by basoundr** [comment]
@davkean Thats true. If #1738 gets through then this will result in merge conflict. So this can wait until that change makes it to dev15,1,x and trickle down to master.

**Comment by basoundr** [comment]
Closing this in favor of #1767

**Pull request closed without merging**
