### PR TITLE
Extracting the code element name from the filepath

### LINKED ISSUE #599: Rename has a confusing message
image

Bar.cs isn't a code element, the "Bar" class is.

### PR DESCRIPTION
**Pull request by jinujoseph**
fixes #599 

New message looks like
image

### CODE REVIEW

**Comment by jinujoseph** [comment]
@dotnet/project-system @srivatsn for review

**Comment by 333fred** [comment]
@jinujoseph you'll have to add the Ask Mode template for approval.

**Comment by jinujoseph** [comment]
@MattGertz for approval.
Customer scenario - When a customer rename a file, they are prompted with a UI to confirm if they want to rename the code element too. We were displays the entire file path instead of just code element.
Bugs this fixes - #799
Workarounds - None
Risk - None

**Comment by MattGertz** [comment]
@jinujoseph Ping me again when second CR is done -- thanks!

**Pull request merged**
