### PR TITLE
Remove 'ByVal' as this is the default parameter modifier.

### PR DESCRIPTION
**Pull request by AdamSpeight2008**
This is a big but simple change of removing `ByVal` from method parameters, as this is the implicit default parameter modifier.

### CODE REVIEW

**Comment by paul1956** [comment]
With this be automatic? On Save? On Edit? How are existing projects affected? Will it to Optional (not that I think it should be)?

**Comment by AdamSpeight2008** [comment]
@paul1956  Look at the diff, it only removes `ByVal` from the parameters, as it the default. 'ByRef` parameters are unaffected. It affects the source code in this repo.

**Comment by AdamSpeight2008** [comment]
@dotnet-bot retest this please

**Comment by davkean** [comment]
tag @dotnet/project-system 

@333fred Can you review this please? It's too big for GitHub, so you'll need to look at it offline.

**Comment by AdamSpeight2008** [comment]
Shouldn't any behaviour changes, this ran the code fix over the solution.

**Comment by 333fred** [comment]
:shipit: Thanks for the contribution @AdamSpeight2008

**Pull request merged**
