### PR TITLE
Suffix async methods with "async"

### PR DESCRIPTION
**Pull request by davkean**
Fixes: #891

Found https://github.com/dotnet/roslyn/issues/16003 and https://github.com/dotnet/roslyn/issues/16004 as a result of this.

Note: This was quite painful to use as there's no fix all and it doesn't run outside of open files. To find these instances, I basically had to have VS open every single file and wait for it to be logged to the Error List.

### CODE REVIEW

**Comment by davkean** [comment]
Tag @dotnet/project-system @BillHiebert @srivatsn 

@BillHiebert @srivatsn Note this changes a public API on ILaunchSettingsProvider - how do I find out who is using this? Had a look around the tree, and can't find any consumers of it.

@weidazhao Does your team call this API?

**Comment by weidazhao** [comment]
@davkean , yes, we're using the API.

**Comment by davkean** [comment]
@weidazhao Okay, so how do we coordinate this change so that we don't break you? How are you consuming us today?

**Comment by weidazhao** [comment]
Docker Tools ships together with .NET Core tooling until VS 2017 RTM at least. Currently we are grabbing binaries from VS 2017 RC. I think we will keep doing the same thing until you guys publish them as NuGet packages to nuget.org.

**Comment by davkean** [comment]
@weidazhao So if I merge this in today/tomorrow, you'll absorb the change tomorrow?

**Pull request merged**
