### PR TITLE
Move project-system VSI jobs to no longer use static machines 

### PR DESCRIPTION
**Pull request by mavasani**
Also move forward the roslyn-internal LKG commit against which our tests are executed.

Similar to roslyn-internal commit: https://github.com/dotnet/roslyn-internal/commit/faee0bb6389989b6811eb95ff1a71d82954b763c

### CODE REVIEW

**Comment by mavasani** [comment]
@dotnet-bot test ci please

**Comment by mavasani** [comment]
Tagging @tannergooding @dotnet/project-system for review.

**Comment by mavasani** [comment]
@srivatsn Does this change also need ask mode approval?

**Comment by srivatsn** [comment]
Infrastructure changes don't

**Pull request merged**
