### PR TITLE
Update BuildAndTest.cmd args for VSI runs to match roslyn-internal

### PR DESCRIPTION
**Pull request by mavasani**
See https://github.com/dotnet/roslyn-internal/blob/master/netci.groovy#L163 for reference.

### CODE REVIEW

**Comment by mavasani** [comment]
@dotnet-bot test ci please

**Comment by mavasani** [comment]
@dotnet-bot test ci please

**Comment by mavasani** [comment]
Tagging @333fred @dotnet/project-system for review

**Comment by 333fred** [comment]
@mavasani, there's a couple of differences between here and there, specifically deployExtensions. Intentional?

**Comment by mavasani** [comment]
@333fred Yes, we need to explicitly set deployExtension=true. This flag basically controls how the VSIX projects in roslyn-internal are deployed by BuildAndTest.cmd:

1. true: deploy them as part of build
2. false: don't deploy as part of build, but instead do it as a post-build step via our custom [VSIXExpInstaller tool](https://github.com/dotnet/roslyn-internal/tree/master/Closed/Tools/Source/VsixExpInstaller). This tool force cleans the destination hive before installing the VSIXes. We don't want this behavior as this will also delete the roslyn-project-system VSIXes that we installed in the previous step. This was just a hack in roslyn-internal to work around the VSIX extension manager bugs in past. I believe we want to remove this soon in Roslyn too.

**Pull request merged**
