### PR TITLE
Inline variable declarations

### PR DESCRIPTION
**Pull request by davkean**
Inlined variable declarations across the tree, dogfooding the new fixer/analysis resulted in the following bugs:

https://github.com/dotnet/roslyn/issues/15994
https://github.com/dotnet/roslyn/issues/15993
https://github.com/dotnet/roslyn/issues/15992

### CODE REVIEW

**Comment by davkean** [comment]
tag @dotnet/project-system

**Comment by davkean** [comment]
Will, as soon as I can figure out how Editor Config support works.

**Comment by mavasani** [comment]
I would say just add an entry in the .ruleset file in the build sub-tree, it will apply for our entire repo.

**Comment by mavasani** [comment]
https://github.com/dotnet/roslyn-project-system/blob/master/build/Rulesets/Roslyn.ruleset

**Pull request merged**
