### PR TITLE
Don't initialize the file watcher in the MEF constructor.

### PR DESCRIPTION
**Pull request by srivatsn**
Making a COM call in the MEF constructor can potentially cause deadlocks. At the very least it can perf problems by blocking background initialization.

@dotnet/project-system @lifengl

### CODE REVIEW

**Comment by srivatsn** [comment]
Tagging @MattGertz. for approval.

**Comment by lifengl** [comment]
Looks good to me

**Comment by MattGertz** [comment]
@srivatsn Can you add the ASK/Escrow info please.

**Comment by srivatsn** [comment]
Scenario
Loading a solution could potentially deadlock VS.
Bug
#625 
Workarounds
None
Risk
Low risk, initialization is moved to a UI context.
Performance Impact
None
Regression Analysis
Not a regression. Fault in the original implementation.

**Comment by MattGertz** [comment]
@srivatsn Sorry, still unclear on one point -- under what scenarios will it deadlock?  What kinds of projects are affected -- is this endemic to all CPS projects?  The above says "Making a COM call in the MEF constructor can potentially cause deadlocks" but I'm not clear when that actually happens, or how frequent.

**Comment by srivatsn** [comment]
Yes all CPS .NET Core projects can potentially deadlock during solution load (when the file watcher gets initialized). Not sure how often it happens but CPS's perf tests are showing this blocking initialization and slowing down solution load as well.

**Pull request merged**
