### PR TITLE
Fix layout of advanced build settings

### PR DESCRIPTION
**Pull request by davkean**
- Aligned labels with checkbox
- Reduced space between last row and previous row
- Changed labels to sentence case
- Changed word slightly

Before:
image

After:
image

Tagged:
image

### CODE REVIEW

**Comment by davkean** [comment]
This includes https://github.com/dotnet/roslyn-project-system/pull/173, so for actual changes - see last two commits #82786c1 and #00868d5

**Comment by davkean** [comment]
tag @dotnet/roslyn-analysis

**Comment by davkean** [comment]
Any remember the magic incantation in the comments section mark resources as "non-localizable"? Looks like error reporting and debugging information aren't expected in the code to be localized.

**Comment by davkean** [comment]
These four commits make up the changes:
https://github.com/dotnet/roslyn-project-system/pull/175/commits/82786c1c1aa2700f44c8ea952382423dff823471
https://github.com/dotnet/roslyn-project-system/pull/175/commits/00868d53992e6090c58767a3dcf311f2ada6124d
https://github.com/dotnet/roslyn-project-system/pull/175/commits/a0e3246dbbf3042a94bfc4f74b12479ccf6a161a
https://github.com/dotnet/roslyn-project-system/pull/175/commits/9fc45337d240fd4421d86101b851268e8ea60563

I removed an extra 3 "designer" px from the dialog that hosts the control to reduce space between buttons and page:
image

**Comment by davkean** [comment]
Side note, those buttons aren't currently "AutoSized" - trying to figure out how to do that nicely with dynamically added controls (the content of the dialog), without double auto-sizing it.

**Comment by davkean** [comment]
This has been updated.

**Comment by srivatsn** [comment]
👍

**Comment by davkean** [comment]
I figured out how to not localize these strings @jinujoseph, got to figure out the real localization for these here: https://github.com/dotnet/roslyn-project-system/issues/52.

**Comment by jinujoseph** [comment]
:+1:

**Pull request merged**
