### PR TITLE
Update the Build and Assembly version from X.0 to X.1

### PR DESCRIPTION
**Pull request by basoundr**
X being 15 for VS component and X being 2 for Roslyn Component

@davkean @dotnet/project-system for review

### CODE REVIEW

**Comment by basoundr** [comment]
@MattGertz fyi. Without this change, the product version of the assembly we insert will have the same version (2.0.1.X and 15.0.1.X) as RTM's, instead of 2.1.1.X & 15.1.1.X

**Comment by MattGertz** [comment]
@basoundr Which deliverable is this for?

**Comment by MattGertz** [comment]
Yes, we need to take this if we take any other bug for project-system in 15.1, such as VSO #393230/GH 1732.

**Comment by tannergooding** [comment]
@basoundr, shouldn't it be x.1.0 and not x.1.1?

**Comment by basoundr** [comment]
Thats true, we can downgrade that portion of the version

**Comment by basoundr** [comment]
@jasonmal Closing this PR since I have included the commits into #1732

**Pull request closed without merging**
