### PR TITLE
Output type property fixes

### PR DESCRIPTION
**Pull request by RaulPerez1**
Fixes the following issues:
#1298 - Return null on OutputTypeEx SetValue so that the value is not propagated to the project
#1299 - Change all references of case insensitive values for OutputType to be case sensitive
#1300 - Use the correct object for the project property on Set so that it's not written as config specific

### CODE REVIEW

**Comment by 333fred** [comment]
Does this have any effect on https://github.com/dotnet/roslyn-project-system/issues/1378?

**Comment by RaulPerez1** [comment]
@333fred - No, that one is most likely because that property only exists on one of the rules page and not on both. I haven't looked at it yet but I did repro it on top of my changes.

**Comment by 333fred** [comment]
@RaulPerez1, with the `Visible="False"` changes this doesn't appear to work correctly any more. I verified that it was working before those changes, and that it doesn't work after them. The property pages are asserting with Debug bits here: https://github.com/dotnet/roslyn-project-system/blob/8cc2ab876de823c589ccb53296fb437c2f08343d/src/Microsoft.VisualStudio.Editors/ResourceEditor/ResourceSerializationService_Store.vb#L521.

**Comment by RaulPerez1** [comment]
That is most likely due to the limited scope of that fix. Now that the property is hidden it has a different descriptor and most likely is not implementing an interface. I'll follow up with CPS after I update to a newer build.

**Comment by RaulPerez1** [comment]
Closing this in lieu of #1709, I'll send out the fix for #1299 separately.

**Pull request closed without merging**
