### PR TITLE
Resize/layout the build events page

### PR DESCRIPTION
**Pull request by davkean**
This resizes the build events page to a size similar to the Build page.
Also lined up the labels to match the controls.

Before:
image

After:
image

### CODE REVIEW

**Comment by davkean** [comment]
This is dependent on https://github.com/dotnet/roslyn-project-system/pull/173, only the last commit is https://github.com/dotnet/roslyn-project-system/pull/176/commits/e22f4c0dc5c90f2e4fbe0ade80080ea47b8847af is interesting.

**Comment by davkean** [comment]
tag @dotnet/roslyn-analysis

**Comment by srivatsn** [comment]
👍

**Comment by asbjornu** [comment]
Awesome! Is it possible to change the default font of these text boxes to a monospace as well?

**Comment by davkean** [comment]
@asbjornu Interesting idea, can you file it?

**Pull request merged**
