### PR TITLE
Project file temp is now put in a temp folder, named correctly. 

### LINKED ISSUE #704: Edit csproj to add a package and then close the file , prompts for wrong filename
image

Environment data

d15rel/15.0.25902.2
1.0.0-preview3-004040

### PR DESCRIPTION
**Pull request by 333fred**
This fixes #704. Old structure:
`%TEMP%\tmp.1234.csproj`
New structure:
`%TEMP%\tmp.1234\ConsoleApp1.csproj`.

Tagging @dotnet/project-system @jinujoseph for review.

### CODE REVIEW

**Comment by 333fred** [comment]
Screenshot of the dialog now:
image

**Comment by 333fred** [comment]
@dotnet/project-system could I get a review please?

**Comment by jinujoseph** [comment]
👍

**Comment by MiaomiaoHuangfu** [comment]
The issue is fixed on build d15rel/26007.00.

**Pull request merged**
