### PR TITLE
Remove the workaround for handling non-rooted target paths in Languag…

### LINKED ISSUE #607: Remove target path workaround for unrestored state once Roslyn can handle null or invalid bin target path
See https://github.com/dotnet/roslyn-project-system/pull/534#discussion_r83274783 and underlying Roslyn bug: https://github.com/dotnet/roslyn/issues/14520

### PR DESCRIPTION
**Pull request by mavasani**
…eService

Underlying Roslyn bug https://github.com/dotnet/roslyn/issues/14520 has been fixed to handle this case.
Fixes #607

### CODE REVIEW

**Comment by mavasani** [comment]
@davkean @dotnet/project-system for review

**Comment by mavasani** [comment]
Ping, any concerns here? It's a trivial PR that only deletes code :)

**Comment by davkean** [comment]
👍  

That code clearly went in while I was away - pretty sure I pushed back on it a number of times :)

**Comment by mavasani** [comment]
@davkean Yes :) it was a temporary workaround.

**Pull request merged**
