### PR TITLE
Resize and fix layout of Debug property page

### PR DESCRIPTION
**Pull request by davkean**
- Moved it from 2.0 code gen -> 4.0
- Aligned labels with controls
- Moved to sentence case for headings
- Resized it to be larger and similar size to Build
- Converted "..." -> "Browse"
- Moved hosting process to under "Start options"
- Changed Working Directory to TextBoxWithWorkaroundForAutoCompleteAppend to fix CTRL+A

Before:
image

After:
image

Tagged:
image

### CODE REVIEW

**Comment by davkean** [comment]
tag @dotnet/roslyn-analysis 

This is dependent on https://github.com/dotnet/roslyn-project-system/pull/173, the following commits are new:

https://github.com/dotnet/roslyn-project-system/pull/179/commits/92f1113d81059cd4a8258bcbd0263cdf57f41863
https://github.com/dotnet/roslyn-project-system/pull/179/commits/0d016a03f5fb3e506b081c2c7713bc00c94ea75d

**Comment by davkean** [comment]
This has been updated

**Comment by srivatsn** [comment]
👍

**Comment by asbjornu** [comment]
Can the default font in the multi-line text boxes please be changed to monospace?

**Pull request merged**
