### PR TITLE
Remove the NgenApplication property

### PR DESCRIPTION
**Pull request by basoundr**
Following the recommended from VSSDK documentation.

@tannergooding @srivatsn @dotnet/project-system for review

### CODE REVIEW

**Comment by basoundr** [comment]
Performing the same as [Roslyn/15808](https://github.com/dotnet/roslyn/pull/15808)

**Comment by basoundr** [comment]
I am not really sure if this change is required for Ngen to work. This is just removal of redundant information. @tannergooding could you please confirm?

**Comment by basoundr** [comment]
@dotnet-bot retest this please

**Comment by basoundr** [comment]
@mmitche This is happening again. Jenkins tests have not started for this change.

**Comment by mavasani** [comment]
@basoundr The change on Roslyn was performed as we started to fail NGEN for Roslyn assemblies, causing multiple RPS regressions.

**Comment by basoundr** [comment]
@MattGertz approval for RC3

**Comment by basoundr** [comment]
@mavasani I was just looking at D15Prerel and the last insertion was made Nov 28th build which does contain the other changes to the Ngen. So the current component that goes with D15Prerel should be fine.

**Comment by MattGertz** [comment]
@basoundr Please tag me again when you have the second approval.

**Comment by basoundr** [comment]
@MattGertz for approval

**Pull request merged**
