### PR TITLE
Fix the output type enum values for class libraries

### PR DESCRIPTION
**Pull request by srivatsn**
The output type value for class libraries is "Library" and not "dll" as the CPS XAML files defines it. Also I had the enum values wrong which caused the wrong values to get selected in the OutputType combobox of the app property page.

@dotnet/project-system

### CODE REVIEW

**Comment by mavasani** [comment]
You need to fix the tests, otherwise LGTM

**Comment by mavasani** [comment]
👍

**Comment by davkean** [comment]
:+1: 

What happens if I have a outputtype of "Bar"? Does the page crash?

**Comment by srivatsn** [comment]
Added some catch clauses to make the prop page not crash for unexpected values. csproj seems to just choose windowsexe (value 0) in such cases which is what we'll do now.

**Pull request merged**
