### PR TITLE
Fix accessibility issues with Advanced Services property page...

### PR DESCRIPTION
**Pull request by KevinH-MS**
- Tab index order was not complete/correct
- A couple controls lacked accessible names (and appropriate names could
not be inferred)

Fixes:  https://devdiv.visualstudio.com/DevDiv/_workitems?id=386365&fullScreen=true&_a=edit

### CODE REVIEW

**Comment by KevinH-MS** [comment]
FYI @Tanya-Solyanik @dpoeschl 
/CC @dotnet/project-system

**Comment by dpoeschl** [comment]
The title of that work item is "Name property is incorrect for edit field in Advanced Settings for Service window" -- did you find other issues there and fix them, or did you actually fix more filed issues than just the one? (Or am I missing something?)

**Comment by KevinH-MS** [comment]
@dpoeschl The VSO bug only pointed out 1 control with this issue, but went on to say "Name property should be appropriate, it should not be null".  I noticed that 2 other controls on this page had the same issue, so I just went ahead and fixed those too.

**Comment by dpoeschl** [comment]
Perfect, thanks! :smile:

**Comment by Tanya-Solyanik** [comment]
What was wrong with the tab order? Labels don't receive focus at all and I think this change is ignored, but now you have 2 elements with tabindex=2. Did you confirm that focus transitions correctly?

**Comment by Tanya-Solyanik** [comment]
I see, Alt-T wasn't working

**Comment by KevinH-MS** [comment]
@Tanya-Solyanik yeah, I confirmed that focus transitions while pressing Tab still work correctly after this change.  You're correct that the label never receives focus, but the TabIndex needs to be equal to the TabIndex of the edit control (or immediately precede the TabIndex of the edit control) in order for the edit control to "inherit" the label text as the MSAA name.

Based on your experience, if it seems better to have all the TabIndex(s) unique, I can increment the index of the controls following the label (I was just going with the minimal change here, because I'm a bit naïve about all the implications).  If I am to change all the TabIndexes, I do wonder how to deal with '0' (zero).  There was originally 3 controls sharing that:
1. The first checkbox
2. The label modified here
3. The layout panel containing custom connection string controls

Is it "ok" for 1 and 3 to both share TabIndex '0', or should the TabIndex for the layout panel be something > 0 but less than its child controls?

**Comment by davkean** [comment]
@KevinH-MS Just for to reduce the diff between when using the designer and manually writing this like you are now - do what the designer does when you turn on tab ordering; each container's children starts from 0 regardless of what the tab order the parent is.

**Pull request merged**
