### PR TITLE
Remove workaround in PropertyControlData for a CPS bug that has been …

### LINKED ISSUE #289: Remove workaround in PropertyControlData when CPS bug is fixed
See https://github.com/dotnet/roslyn-project-system/pull/287#discussion_r69661778

### PR DESCRIPTION
**Pull request by mavasani**
…fixed

Fixes #289

### CODE REVIEW

**Comment by mavasani** [comment]
Tagging @dotnet/project-system for review

**Comment by davkean** [comment]
Fixed in which build?

**Comment by mavasani** [comment]
@srivatsn tells me its been fixed. Also this workaround is causing this crash: [244048](https://devdiv.visualstudio.com/DevDiv/_workitems?id=244048&_a=edit)

**Comment by srivatsn** [comment]
It was fixed a while ago in vscore.dev.

**Comment by davkean** [comment]
While I'm fine with the change itself, a couple of things:

1) the fact that this is tearing down VS worries me. Did we regress something here? CheckoutException is supposed to throw on this path and be *handled*. Can you try a read-only project, make a change that goes down this path and then cancel the overwrite? Do we crash VS?

2) Looks like their extender is broken - given what we set is the same value that they return.

**Comment by mavasani** [comment]
So, I verified couple of things -

1. The CheckoutException seems to go unhandled in the below call stack and is specific to UniversalDebugPropertyPage. Our own property pages handle this exception gracefully.

2. The exception will repro for this page even after this fix for the scenario Dave mentioned above, though it won't repro for the scenario in VSO 244048. I am not sure whose responsibility it is here to handle this exception.

```
Microsoft.VisualStudio.AppDesigner.dll!Microsoft.VisualStudio.Editors.PropertyPages.PropertyControlData.PropertyDescriptorSetValueHelper.SetValue(System.ComponentModel.PropertyDescriptor Descriptor, object Component, object Value)      Unknown
Microsoft.VisualStudio.AppDesigner.dll!Microsoft.VisualStudio.Editors.PropertyPages.PropertyControlData.SetNonCommonPropertyValueCore(object Value)   Unknown
Microsoft.VisualStudio.AppDesigner.dll!Microsoft.VisualStudio.Editors.PropertyPages.PropertyControlData.SetPropertyValue(object Value)   Unknown
Microsoft.VisualStudio.UniversalLibrary.dll!Microsoft.VisualStudio.UniversalLibrary.ProjectFlavoring.UniversalDebugPropertyPage.AuthenticationModeCombo
```

**Comment by davkean** [comment]
Did we file a bug against them? Because the checkout exception, presumably will happen on a normal path, such as someone cancelling the checkout of a project file.

**Comment by mavasani** [comment]
Where should I file a bug? VSO - what area path?

**Pull request merged**
