### PR TITLE
Fix for 1406 and 1250, don't allow to remove implicit SDK dependency

### LINKED ISSUE #1406: Attempting to remove the framework reference results in an Assert
1. File -> New Class Library (.NET Standard)
2. Expand Dependency -> SDK
3. Right-click on .NETStandard.Library and choose remove

Expected: To not be able to remove it
Actual:

```
---------------------------
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue
---------------------------
Cannot find reference to remove.



   at Microsoft.Report.Fail(String message)

   at Microsoft.Report.IfNot(Boolean condition, String message)

   at Microsoft.VisualStudio.ProjectSystem.VS.Tree.Dependencies.DependenciesProjectTreeProvider.<RemoveAsync>d__17.MoveNext()

   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(Object stateMachine)

   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()

   at System.Threading.Tasks.SynchronizationContextAwaitTaskContinuation.<>c.<.cctor>b__8_0(Object state)

   at Microsoft.VisualStudio.Threading.AsyncReaderWriterLock.NonConcurrentSynchronizationContext.<PostHelper>d__9.MoveNext()

   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(Object stateMachine)

   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()

   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining, Task& currentTask)

   at System.Threading.Tasks.Task.FinishContinuations()

   at System.Threading.Tasks.Task.FinishStageThree()

   at System.Threading.Tasks.Task`1.TrySetResult(TResult result)

   at System.Threading.SemaphoreSlim.TaskNode.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()

   at System.Threading.ThreadPoolWorkQueue.Dispatch()

   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()


---------------------------
Abort   Retry   Ignore   
---------------------------
```

### LINKED ISSUE #1412: Attempting to set a property on SDK results in an error
1. File -> New -> Console App (.NET Core)
2. Choose Microsoft.NETCore.App
3. In Properties attempt to change on of the values:

image

An error has occurred while saving the edited properties listed below:
	Copy Payload
One or more values are invalid. Specified method is not supported.

### PR DESCRIPTION
**Pull request by abpiskunov**
**Customer scenario**

When user right clicks on implicit SDK or (former package) reference there is error saying that its not possible to remove it. Also if they try to set some properties, that leads to an error as well.

**Bugs this fixes:**

Fixes #1406 Fixes #1412 
https://github.com/dotnet/roslyn-project-system/issues/1250

**Workarounds, if any**

No

**Risk**

Minimal

**Performance impact**

None

**Is this a regression from a previous update?**

No

### CODE REVIEW

**Comment by abpiskunov** [comment]
@srivatsn @davkean  This is not approved for RTM, but just showing you the PR in case you want it in. Change is easy and safe, and error is visible :)

**Comment by abpiskunov** [comment]
Added another SDK related easy fix for https://github.com/dotnet/roslyn-project-system/issues/1412 , made all SDK properties readonly - users don't need to edit them any way.

**Comment by srivatsn** [comment]
Tagging @MattGertz  for approval.

**Comment by natidea** [comment]
Approved to merge via [378771](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/378771)

**Pull request merged**
