### PR TITLE
Adding size of unzipped package extensions

### PR DESCRIPTION
**Pull request by jmarolf**

### CODE REVIEW

**Comment by davkean** [comment]
Hmm, this is just going to get out of sync - can we populate this automatically?

**Comment by jmarolf** [comment]
@davkean this gets calculated automatically if you build a V3 vsix.  Once we move to that this won't be an issue.

**Comment by jmarolf** [comment]
retest windows_release_prtest please

reason [Flaky Test](https://github.com/dotnet/roslyn-project-system/issues/431)

**Comment by davkean** [comment]
retest Windows Release please

**Comment by davkean** [comment]
:+1:

**Comment by basoundr** [comment]
:+1:

**Pull request merged**
