### PR TITLE
Add 3pn entry for dotnet/cli

### PR DESCRIPTION
**Pull request by richlander**
- Due to https://github.com/dotnet/roslyn-project-system/blob/master/src/Microsoft.VisualStudio.ProjectSystem.CSharp.VS/ProjectSystem/VS/Xproj/MigrationError.cs#L9

### CODE REVIEW

**Comment by davkean** [comment]
Can we remove this when that file is deleted?

**Comment by 333fred** [comment]
Will that file be deleted?

**Comment by davkean** [comment]
To remove the 3rd party notice, we could clean room the implementation.

**Comment by richlander** [comment]
That would be a poor use of time. Almost all of our repos have these notices.

_Definition of ridiculous:_ A clean room implementation of a Microsoft-create type by another Microsoft team.

**Comment by davkean** [comment]
It's a single type that causes us to add a 3rd party notice.

**Comment by richlander** [comment]
Sure, but you'll likely have more entries over time. There is no desire to reduce these.

For example, does this project have a dependency on roslyn?

**Comment by davkean** [comment]
We have a NuGet dependency on Roslyn? What's the relevance?

**Comment by richlander** [comment]
Not. Sounds good. Maybe you'll end up a pretty limited 3PN after all.

**Pull request merged**
