### PR TITLE
Adding a check to make sure certain API's are being called from UI thread.

### PR DESCRIPTION
**Pull request by jinujoseph**
Related to #109

### CODE REVIEW

**Comment by jinujoseph** [comment]
@davkean

**Comment by basoundr** [comment]
:+1: 

On a side note, [Codeing Conventions](https://github.com/dotnet/roslyn-project-system/blob/master/docs/repo/Coding%20Conventions.md) mention that, "For MEF parts/components, we favor constructor injection over property/field injection". In this PR, the injection is done over constructor, whereas in [AbstractLanguageServiceHost](https://github.com/dotnet/roslyn-project-system/blob/master/src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/LanguageServices/AbstractLanguageServiceHost.cs#L102) I see a bunch of Property injection(there might be other places).

**Comment by davkean** [comment]
No tests?

@basoundr AbstractLanguageServiceHost was a port, so it doesn't follow the conventions. This is correct.

**Comment by natidea** [comment]
:shipit:

**Pull request merged**
