### PR TITLE
Remove unused using

### PR DESCRIPTION
**Pull request by davkean**
tag @dotnet/project-system

### CODE REVIEW

**Comment by davkean** [comment]
@dotnet-bot test vsi please

**Comment by tannergooding** [comment]
@davkean, VSI tests are on the floor right now (license expired). It should be fixed as soon as the new image is up (its copying to the appropriate storage accounts now).

**Comment by davkean** [comment]
@tannergooding They are failing for other reasons right now.

**Comment by 333fred** [comment]
@tannergooding @davkean you're both right? If our vsi tests on this branch were actually working right, then we'd be hitting the license issue too.

**Pull request merged**
