### PR TITLE
Ensure that TargetFrameworkProjectConfigurationDimensionProvider gets…

### PR DESCRIPTION
**Pull request by mavasani**
… loaded with ImplicitProjectConfigurationsService by adding the matching capability

### CODE REVIEW

**Comment by mavasani** [comment]
@davkean @dotnet/project-system for review.

**Comment by davkean** [comment]
👍

**Comment by jinujoseph** [comment]
👍

**Comment by davkean** [comment]
Can we file a bug to make sure we move to Lifeng's change?

**Comment by davkean** [comment]
Long term this type should not be marked with this capability.

**Comment by mavasani** [comment]
Filed https://github.com/dotnet/roslyn-project-system/issues/559 and also added a comment about introducing a new capability for TargetFrameworkProjectConfigurationDimensionProvider

**Pull request merged**
