### PR TITLE
Allow displaying of Settings page based on AppDesigner capability

### PR DESCRIPTION
**Pull request by RaulPerez1**
**Customer scenario**

When editing project properties some of the pages should not be showing up for .Net Core apps. There's been reports of customers running into crashes or broken experience issues when trying to make edits to the unsupported pages. This change conditions the page to show up via a capability which is enabled for .NetFramework projects.

**Bugs this fixes:**
#572 

**Workarounds, if any**
No workarounds, currently the page will always show.

**Risk**
Low Risk - This only affects the settings page.

**Performance impact**
Low - This is not under a critical path and it adds an extra capability check which is inexpensive.

**Is this a regression from a previous update?**
Not a regression, previously the page applied to all projects which isn't true anymore.

**Root cause analysis:**
See above.

**How was the bug found?**
Dogfooding

### CODE REVIEW

**Comment by RaulPerez1** [comment]
The latest changes are still missing where we set/remove the capability. I started a conversation to figure that part out.

**Comment by srivatsn** [comment]
Tagging @MattGertz for approval.

**Comment by 333fred** [comment]
I'd like @davkean to look at the syntax for the capabilities and make sure it looks good, but otherwise LGTM.

**Comment by natidea** [comment]
Approved to merge via [377662](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/377662)

**Pull request merged**
