### PR TITLE
Listen to active configured project changes in ConfiguredProjectReady…

### PR DESCRIPTION
**Pull request by mavasani**
…ToBuild

**Customer scenario**

1. Create an ASP.NET Core Web Application ("Web Application" template)
2. Ctrl+F5 
3. Change the Solution Configuration from "Debug" to "Release"

VS Hangs. (If it doesn't, try changing the configuration again. It will hang eventually.) I could quite consistently get a hang with the repro steps, once in 2-3 attempts.

**Bugs this fixes:**

This fixes VSO [367498](https://devdiv.visualstudio.com/DevDiv/_workitems/index?_a=edit&id=367498&triage=true)

**Workarounds, if any**

None.

**Risk**

None. This provider is invoked by the CPS design time build project snapshot service when deciding whether or not a configured project is ready to be built. We were not listening to active configuration changes, causing us to intermittently cause a deadlock on project configuration change.

Testing: After the fix, I see no hang after numerous attempts.

**Performance impact**

This should have no performance impact.

**Is this a regression from a previous update?**

No, this feature was implemented recently.

**Root cause analysis:**

This is a race condition which occurs intermittently. We probably needed more rigorous testing around this scenario.

**How was the bug found?**

Customer reported/dogfooding.

### CODE REVIEW

**Comment by mavasani** [comment]
Tagging @lifengl @dotnet/project-system for review

**Comment by mavasani** [comment]
Ping, can I get another review?

**Comment by mavasani** [comment]
Ping, can I get another review?

**Comment by mavasani** [comment]
Tagging @MattGertz for RTM approval.

**Comment by lifengl** [comment]
Your change looks good to me.


Unrelated to this change, it is better to create your own object to control the lock region, instead of using configured project node, which is more likely introducing dead locks.  Also you called SetResult inside your lock region, because it will execute code inline the block, it will increase the risk of dead locks as well.


Of course, it doesn't meet the bar to address those issues without seeing any dead locks.  Just mention it, so we can reduce those patterns in the future.


________________________________

**Comment by natidea** [comment]
@MattGertz this change is targeting RTW. Could we get the proactive merge label as well?

**Pull request merged**
