### PR TITLE
Added strings for the edit csproj dialogs.

### PR DESCRIPTION
**Pull request by 333fred**
Added dialog strings for needing to reload the project file and saving changes to the project file on close. Screenshots:

image
image

### CODE REVIEW

**Comment by davkean** [comment]
What is the later dialog?

**Comment by 333fred** [comment]
If there are unsaved changes in the buffer on buffer close. We can't just reuse the existing editor logic as there's no real backing file for the editor any more.

**Comment by davkean** [comment]
So what happens if I have 5 projects with unsaved changes? We prompt 5 times?

**Comment by 333fred** [comment]
At present, yes. All of the state machine logic is at the project level, so we'd have to create a machine to live at the solution level to consolidate that.

**Comment by davkean** [comment]
Let's talk offline - we really should be opt'ing into the existing infrastructure

**Pull request closed without merging**
