### PR TITLE
Fix mocking method with out parameter returned no result

### PR DESCRIPTION
**Pull request by davkean**
- Fix mocking method with out parameter returned no result
- Add ability to mock methods with two out params

### CODE REVIEW

**Comment by davkean** [comment]
tag @dotnet/project-system

**Comment by basoundr** [comment]
Are these extensions being used by anyone?

**Comment by 333fred** [comment]
I would have used them if I knew they were there, I have a few out params to mock.

**Comment by davkean** [comment]
And I'm using them in some tests I wrote.

**Pull request merged**
