### PR TITLE
Fix dogfood VSIX to opt into project system

### PR DESCRIPTION
**Pull request by davkean**
The keys changed, fix them so that we opt into csproj for F5.

### CODE REVIEW

**Comment by davkean** [comment]
tag @dotnet/roslyn-infrastructure @srivatsn

**Comment by srivatsn** [comment]
👍

**Comment by 333fred** [comment]
Do we need to capitalize these in the CS/VB packages as well?

**Comment by davkean** [comment]
No it doesn't really matter, I just did it because of my OCD.

**Pull request merged**
