### PR TITLE
Jenkins groovyfile

### PR DESCRIPTION
**Pull request by johnbeisner**
Modifying Roslyn-Project-System Jenkin's groovy file: 
1. explicitly setting the 'refspec' in order to locate the PR content. line#208+
2. moving the Rosyln-Internal commit-pointer forward. line#236
3. *trivial* modifying comments and formatting

### CODE REVIEW

**Comment by 333fred** [comment]
@johnbeisner rather than individually merging these, we should just merge master into post-dev15.

**Comment by mavasani** [comment]
I agree with Fred

**Comment by johnbeisner** [comment]
@333fred "master into post-dev15" for just this one file or ALL of master to post-dev15. And if it is the latter, who does these types integrations for our team; anyone? What kind of approval do I need?

**Comment by 333fred** [comment]
All of master. I've asked @dotnet/roslyn-infrastructure to turn on the merge pump, but they haven't had time to do that currently, so we've just been doing it manually. As for approval, just the standard 2 approvals.

**Comment by davkean** [comment]
Turning on the merge pump used to be a one line change...

**Pull request merged**
