### PR TITLE
VisualStudioDogfoodSetup is dead, long live VisualStudioDogfoodSetup

### PR DESCRIPTION
**Pull request by davkean**
This now was only being used to register a trace listener. Moved it to the managed package and #if it out so that it's only enabled under DEBUG.

### CODE REVIEW

**Comment by davkean** [comment]
tag @dotnet/project-system

**Comment by basoundr** [comment]
@davkean the change looks good except for the build failure

**Comment by davkean** [comment]
@dotnet-bot retest this please

**Comment by davkean** [comment]
Build failure was caused by: https://github.com/NuGet/Home/issues/4845.

**Pull request merged**
