### PR TITLE
Remove Reload workaround and use official API (target Dev15-RC3)

### PR DESCRIPTION
**Pull request by jviau**
Consumes the new msbuild feature: [https://github.com/Microsoft/msbuild/pull/1507](https://github.com/Microsoft/msbuild/pull/1507)

### CODE REVIEW

**Comment by srivatsn** [comment]
Tagging @MattGertz. This is a response to a MSBuild change that preserves comments and whitespace in the file.

Customer Scenario: 
If the users edits the csproj file from the editor, adds a comment and saves, the comment will be lost. 

**Bugs this fixes:**

**Workarounds, if any**

Edit outside the IDE.

**Risk**

Low for this change - we are reacting to a msbuild change.

**Performance impact**

Low for this change - we are directly calling msbuild which is doing roughly the same amount of work.

**Is this a regression from a previous update?**

No. 

**Root cause analysis:**

MSbuild didn't preserve trivia before and now it does.

**How was the bug found?**

Customer reports

**Comment by natidea** [comment]
We did not discuss this in shiproom today, so we will bring it tomorrow

**Comment by natidea** [comment]
Approved to merge

**Comment by jviau** [comment]
After discussion with @cdmihai I realized I needed to keep the `project.Save(new StringWriter())` behavior.

**Comment by davkean** [comment]
@jviau Why? That is completely unobvious and someone's going to remove that in the future thinking that it's a mistake.,

**Comment by davkean** [comment]
Oh because the comment about it is still relevant?

**Comment by jviau** [comment]
@davkean yes, a Reload sets `HasUnsavedChanges` to true.

**Comment by davkean** [comment]
Which seems like a bug, right @cdmihai?

**Comment by natidea** [comment]
@jviau or @davkean, is this ready to go so we can start the insertion?

**Comment by davkean** [comment]
We can merge the change in, but I think we should get a bug on the dirty flag @cdmihai?

**Comment by natidea** [comment]
Merging to start insertion

**Comment by cdmihai** [comment]
@davkean 
Yes, I've opened https://github.com/Microsoft/msbuild/issues/1554
Though only 2 of the 3 Reload overloads need to ensure there are no unsaved changes. The overload that's reloading from an XmlReader still needs to leave the PRE object with unsaved changes, since they may differ from the backing PRE file.

**Pull request merged**
