### PR TITLE
Run tests after tree has built

### PR DESCRIPTION
**Pull request by davkean**
- Run tests after tree has built
- Run targets as individuals so that we get a pretty log/order

Before:
```
  Restoring packages for ProjectSystem (this may take some time)
  Building ProjectSystem [Debug]
  Microsoft.VisualStudio.AppDesigner -> E:\project-system2\bin\Debug\Microsoft.VisualStudio.AppDesigner.dll
  Microsoft.VisualStudio.ProjectSystem.Managed.TestServices -> E:\project-system2\bin\Debug\Tests\Microsoft.VisualStudio.ProjectSystem.Managed.TestServices.dll
  Microsoft.VisualStudio.ProjectSystem.Managed -> E:\project-system2\bin\Debug\Microsoft.VisualStudio.ProjectSystem.Managed.dll
  Microsoft.VisualStudio.ProjectSystem.CSharp -> E:\project-system2\bin\Debug\Microsoft.VisualStudio.ProjectSystem.CSharp.dll
  Microsoft.VisualStudio.ProjectSystem.VisualBasic -> E:\project-system2\bin\Debug\Microsoft.VisualStudio.ProjectSystem.VisualBasic.dll
  Microsoft.VisualStudio.Editors -> E:\project-system2\bin\Debug\Microsoft.VisualStudio.Editors.dll
  SettingsDesignerUnitTests -> E:\project-system2\bin\Debug\Tests\SettingsDesignerUnitTests.dll
  Microsoft.VisualStudio.Editors.UnitTests -> E:\project-system2\bin\Debug\Tests\Microsoft.VisualStudio.Editors.UnitTests.dll
  VisualStudioEditorsSetup -> E:\project-system2\bin\Debug\VisualStudioEditorsSetup.dll
  VisualStudioEditorsSetup -> E:\project-system2\bin\Debug\VisualStudioEditorsSetup.vsix
  Microsoft.VisualStudio.ProjectSystem.Managed.VS -> E:\project-system2\bin\Debug\Microsoft.VisualStudio.ProjectSystem.Managed.VS.dll
  Microsoft.VisualStudio.ProjectSystem.VisualBasic.VS -> E:\project-system2\bin\Debug\Microsoft.VisualStudio.ProjectSystem.VisualBasic.VS.dll
  Microsoft.VisualStudio.ProjectSystem.CSharp.VS -> E:\project-system2\bin\Debug\Microsoft.VisualStudio.ProjectSystem.CSharp.VS.dll
  ProjectSystemSetup -> E:\project-system2\bin\Debug\ProjectSystem.dll
  DeployTestDependencies -> E:\project-system2\bin\Debug\Tests\DeployTestDependencies.dll
  Microsoft.VisualStudio.ProjectSystem.Managed.TestServices.UnitTests -> E:\project-system2\bin\Debug\Tests\Microsoft.VisualStudio.ProjectSystem.Managed.TestServices.UnitTests.dll
  Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests -> E:\project-system2\bin\Debug\Tests\Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests.dll
  Microsoft.VisualStudio.ProjectSystem.VisualBasic.UnitTests -> E:\project-system2\bin\Debug\Tests\Microsoft.VisualStudio.ProjectSystem.VisualBasic.UnitTests.dll
  Microsoft.VisualStudio.ProjectSystem.VisualBasic.VS.UnitTests -> E:\project-system2\bin\Debug\Tests\Microsoft.VisualStudio.ProjectSystem.VisualBasic.VS.UnitTests.dll
  Microsoft.VisualStudio.ProjectSystem.CSharp.UnitTests -> E:\project-system2\bin\Debug\Tests\Microsoft.VisualStudio.ProjectSystem.CSharp.UnitTests.dll
  Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests -> E:\project-system2\bin\Debug\Tests\Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests.dll
  Microsoft.VisualStudio.ProjectSystem.CSharp.VS.UnitTests -> E:\project-system2\bin\Debug\Tests\Microsoft.VisualStudio.ProjectSystem.CSharp.VS.UnitTests.dll
  ProjectSystemSetup -> E:\project-system2\bin\Debug\ProjectSystem.vsix
  ProjectSystemDogfoodSetup -> E:\project-system2\bin\Debug\ProjectSystemDogfoodSetup.dll
  ProjectSystemDogfoodSetup -> E:\project-system2\bin\Debug\ProjectSystemDogfoodSetup.vsix
  Building NuGet packages [Debug]
  Microsoft.VisualStudio.Editors\Microsoft.VisualStudio.Editors.nuspec -> E:\project-system2\bin\Debug\NuGetPackages\Microsoft.VisualStudio.Editors.1.0.0.nupkg
  Microsoft.VisualStudio.AppDesigner\Microsoft.VisualStudio.AppDesigner.nuspec -> E:\project-system2\bin\Debug\NuGetPackages\Microsoft.VisualStudio.AppDesigner.1.0.0.nupkg
  Microsoft.VisualStudio.ProjectSystem.Managed\Microsoft.VisualStudio.ProjectSystem.Managed.nuspec -> E:\project-system2\bin\Debug\NuGetPackages\Microsoft.VisualStudio.ProjectSystem.Managed.1.0.0.nupkg
  Microsoft.VisualStudio.ProjectSystem.Managed.VS\Microsoft.VisualStudio.ProjectSystem.Managed.VS.nuspec -> E:\project-system2\bin\Debug\NuGetPackages\Microsoft.VisualStudio.ProjectSystem.Managed.VS.1.0.0.nupkg
  Running tests for ProjectSystem [Debug]
  All tests passed, for full log see E:\project-system2\bin\Debug\Tests\TestResults.html
  Rebuilding Modern VSIX Packages [Debug]

Build completed successfully, for full logs see E:\project-system2\bin\Debug\Restore.log E:\project-system2\bin\Debug\Build.log E:\project-system2\bin\Debug\BuildModernVsixPackages.log
```

After:
```

  Restoring packages for ProjectSystem (this may take some time)

  Building ProjectSystem [Debug]
  Microsoft.VisualStudio.AppDesigner -> E:\project-system2\bin\Debug\Microsoft.VisualStudio.AppDesigner.dll
  Microsoft.VisualStudio.ProjectSystem.Managed.TestServices -> E:\project-system2\bin\Debug\Tests\Microsoft.VisualStudio.ProjectSystem.Managed.TestServices.dll
  Microsoft.VisualStudio.ProjectSystem.Managed -> E:\project-system2\bin\Debug\Microsoft.VisualStudio.ProjectSystem.Managed.dll
  Microsoft.VisualStudio.ProjectSystem.VisualBasic -> E:\project-system2\bin\Debug\Microsoft.VisualStudio.ProjectSystem.VisualBasic.dll
  Microsoft.VisualStudio.Editors -> E:\project-system2\bin\Debug\Microsoft.VisualStudio.Editors.dll
  Microsoft.VisualStudio.ProjectSystem.CSharp -> E:\project-system2\bin\Debug\Microsoft.VisualStudio.ProjectSystem.CSharp.dll
  Microsoft.VisualStudio.Editors.UnitTests -> E:\project-system2\bin\Debug\Tests\Microsoft.VisualStudio.Editors.UnitTests.dll
  SettingsDesignerUnitTests -> E:\project-system2\bin\Debug\Tests\SettingsDesignerUnitTests.dll
  VisualStudioEditorsSetup -> E:\project-system2\bin\Debug\VisualStudioEditorsSetup.dll
  VisualStudioEditorsSetup -> E:\project-system2\bin\Debug\VisualStudioEditorsSetup.vsix
  Microsoft.VisualStudio.ProjectSystem.Managed.VS -> E:\project-system2\bin\Debug\Microsoft.VisualStudio.ProjectSystem.Managed.VS.dll
  Microsoft.VisualStudio.ProjectSystem.VisualBasic.VS -> E:\project-system2\bin\Debug\Microsoft.VisualStudio.ProjectSystem.VisualBasic.VS.dll
  Microsoft.VisualStudio.ProjectSystem.CSharp.VS -> E:\project-system2\bin\Debug\Microsoft.VisualStudio.ProjectSystem.CSharp.VS.dll
  ProjectSystemSetup -> E:\project-system2\bin\Debug\ProjectSystem.dll
  DeployTestDependencies -> E:\project-system2\bin\Debug\Tests\DeployTestDependencies.dll
  Microsoft.VisualStudio.ProjectSystem.Managed.TestServices.UnitTests -> E:\project-system2\bin\Debug\Tests\Microsoft.VisualStudio.ProjectSystem.Managed.TestServices.UnitTests.dll
  ProjectSystemSetup -> E:\project-system2\bin\Debug\ProjectSystem.vsix
  Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests -> E:\project-system2\bin\Debug\Tests\Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests.dll
  Microsoft.VisualStudio.ProjectSystem.VisualBasic.UnitTests -> E:\project-system2\bin\Debug\Tests\Microsoft.VisualStudio.ProjectSystem.VisualBasic.UnitTests.dll
  Microsoft.VisualStudio.ProjectSystem.CSharp.UnitTests -> E:\project-system2\bin\Debug\Tests\Microsoft.VisualStudio.ProjectSystem.CSharp.UnitTests.dll
  Microsoft.VisualStudio.ProjectSystem.VisualBasic.VS.UnitTests -> E:\project-system2\bin\Debug\Tests\Microsoft.VisualStudio.ProjectSystem.VisualBasic.VS.UnitTests.dll
  Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests -> E:\project-system2\bin\Debug\Tests\Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests.dll
  Microsoft.VisualStudio.ProjectSystem.CSharp.VS.UnitTests -> E:\project-system2\bin\Debug\Tests\Microsoft.VisualStudio.ProjectSystem.CSharp.VS.UnitTests.dll
  ProjectSystemDogfoodSetup -> E:\project-system2\bin\Debug\ProjectSystemDogfoodSetup.dll
  ProjectSystemDogfoodSetup -> E:\project-system2\bin\Debug\ProjectSystemDogfoodSetup.vsix

  Building NuGet packages [Debug]
  Microsoft.VisualStudio.Editors\Microsoft.VisualStudio.Editors.nuspec -> E:\project-system2\bin\Debug\NuGetPackages\Microsoft.VisualStudio.Editors.1.0.0.nupkg
  Microsoft.VisualStudio.AppDesigner\Microsoft.VisualStudio.AppDesigner.nuspec -> E:\project-system2\bin\Debug\NuGetPackages\Microsoft.VisualStudio.AppDesigner.1.0.0.nupkg
  Microsoft.VisualStudio.ProjectSystem.Managed\Microsoft.VisualStudio.ProjectSystem.Managed.nuspec -> E:\project-system2\bin\Debug\NuGetPackages\Microsoft.VisualStudio.ProjectSystem.Managed.1.0.0.nupkg
  Microsoft.VisualStudio.ProjectSystem.Managed.VS\Microsoft.VisualStudio.ProjectSystem.Managed.VS.nuspec -> E:\project-system2\bin\Debug\NuGetPackages\Microsoft.VisualStudio.ProjectSystem.Managed.VS.1.0.0.nupkg

  Rebuilding Modern VSIX Packages [Debug]

  Running tests for ProjectSystem [Debug]
  All tests passed, for full log see E:\project-system2\bin\Debug\Tests\TestResults.html

Build completed successfully, for full logs see E:\project-system2\bin\Debug\Build_Restore.log E:\project-system2\bin\Debug\Build_Build.log E:\project-system2\bin\Debug\Build_BuildNuGetPackages.log E:\project-system2\bin\Debug\Build_BuildModernVsixPackages.log E:\project-system2\bin\Debug\Build_Test.log
```

### CODE REVIEW

**Comment by davkean** [comment]
tag @dotnet/project-system

**Comment by basoundr** [comment]
while you are here, could you fix the message to say `Building Modern VSIX Packages` instead of `Rebuilding Modern VSIX Packages` [here](https://github.com/dotnet/roslyn-project-system/pull/1776/files#diff-961d3b78efb89a2d0733ea8f03924bc8R73)

**Comment by basoundr** [comment]
👍with the comments

**Comment by davkean** [comment]
It doesn't build, it rebuilds - whomever implemented it just calls Rebuild.

**Pull request merged**
