### PR TITLE
Modify public types to internal types

### PR DESCRIPTION
**Pull request by basoundr**
if the types need not be public

@srivatsn @dotnet/project-system for review

### CODE REVIEW

**Comment by basoundr** [comment]
Also should `Microsoft.VisualStudio.ProjectSystem.VS.Utilities.FocusAttacher` be public?

**Comment by basoundr** [comment]
Also this does not include the projects AppDesigner and Editors since I don't know if some of the classes in these projects are expected to be public by design.

**Comment by srivatsn** [comment]
@abpiskunov @weidazhao do you use any of these types?

**Comment by abpiskunov** [comment]
@srivatsn  we don't

**Comment by weidazhao** [comment]
@srivatsn we don't use any types to be changed in this PR either.

**Pull request merged**
