### PR TITLE
Package property page

### PR DESCRIPTION
**Pull request by mavasani**
Add a new property page to enable users to generate NuGet package on build and edit the MSBuild properties specific to the package.

I have broken down the PR into multiple logical commits, with explanation for each change:

1. [REVERTED] https://github.com/dotnet/roslyn-project-system/commit/94afea7057a5523ae309c85237042d475332a6f7: Add new Application property page for C#/VB dotnet core project that hides the AssemblyInfomation button
2. https://github.com/dotnet/roslyn-project-system/commit/d6e7b83d9de6ad76f31725f999ca88261c7a7170: Refactor code out of AssemblyInfoPropPage control into AssemblyInfoUtils so it can be shared with the new Package property page.
3. https://github.com/dotnet/roslyn-project-system/commit/26557f3e347a7efdca18c4d28975d9974d72d33f: Add Package property page and corresponding resource strings. Also hookup the new property pages in the pkgdef.
4. https://github.com/dotnet/roslyn-project-system/commit/41400be9a4d26911f00f58d62420b94fbc457418: Hookup the new property pages in the C# and VB designer page providers 
5. https://github.com/dotnet/roslyn-project-system/commit/d8b922eb1390dfdd62cdbc2fa15fdd4b1052c219: Add browse object properties for new Package property page
6. https://github.com/dotnet/roslyn-project-system/commit/f1ac367635c00ed9955a27cd47d0df98ba28ab4b: Implementation of providers for Package property page properties. 
    1. Switch SourceFilePropertyProvider to ProjectFileOrAssemblyInfoPropertiesProvider - based on the setting of a specific property, we switch between reading/writing the assembly info properties in project file OR source attributes.
    2. Add intercepting property value providers for default values of version specific properties and other properties defaulting to AssemblyName.
7. https://github.com/dotnet/roslyn-project-system/commit/c3d5a3c3c0cf07e860744189ad7db661435b621c and https://github.com/dotnet/roslyn-project-system/commit/90b55f274760970c51317218287df57a923eb2db: Some code cleanup
8. https://github.com/dotnet/roslyn-project-system/commit/8dd0f6969f79833eb0a51150ac1455a53b14425b: Add unit tests for newly added property providers for package property page.

TODO: Add a context menu command to invoke pack explicitly. This will done with a separate PR.

### CODE REVIEW

**Comment by mavasani** [comment]
Here is the screenshot:

image

**Comment by mavasani** [comment]
Tagging @dotnet/project-system for review

**Comment by davidfowl** [comment]
This is nice. One question I have about generate package on build. Is the pack task incremental?

**Comment by davkean** [comment]
Can we not fork the application page please? Instead just hide the button based on a setting/capability/whatever.

**Comment by srivatsn** [comment]
@rrelyea @rohit21agarwal - to @davidfowl 's question - can pack work incrementally?

**Comment by srivatsn** [comment]
I agree we shouldn't fork the app page. Instead just hide the button if the package page is going to show up ( based on a capability maybe?)

**Comment by mavasani** [comment]
@srivatsn @davkean Application page related changes don't affect loc, so I am just going to revert those changes for now. Can you please review the other commits in the PR? I believe we need to check this in by Monday 12/19 for Loc freeze.

**Comment by mavasani** [comment]
FYI: I have reverted all application pages related changes and filed https://github.com/dotnet/roslyn-project-system/issues/977 to hide the button.

**Comment by mavasani** [comment]
Tagging @nguerrera as this needs localization work as well. This PR will likely not be merged this week.

**Comment by mavasani** [comment]
@nguerrera, if we *must* get this in today, I can proactively merge this in and address review feedback with separate PR. I already got UI screenshots sign off from @srivatsn  @davkean  and Rob, so hopefully there are no more UI/Loc changes. Sri, does that sound reasonable?

**Comment by mavasani** [comment]
I am merging this in for loc freeze. Please continue reviewing the PR, I'll open a separate PR to address feedback.

**Comment by rohit21agrawal** [comment]
@davidfowl @srivatsn not sure i understand what you mean by incremental here

**Comment by srivatsn** [comment]
If nothing's changed in the project, will it repack or cause a rebuild?

**Comment by rohit21agrawal** [comment]
it will still call the build target, but i think the build will no-op and it will just re-pack.

**Comment by srivatsn** [comment]
Can it avoid the repacking as well? If a user sets this flag to pack on build, then every build will do non-trivial work.

**Comment by rohit21agrawal** [comment]
it can't do that right now, you can file this as a feature request, will have to come up with a plan on when Pack should no-op. I agree, it would be nice to have this feature..

**Comment by davkean** [comment]
Incremental isn't a feature request - it's a requirement of the of build.

**Comment by rohit21agrawal** [comment]
if build can figure out when it no-ops, can it not be configured to not call pack when it is a no-op?

**Comment by davkean** [comment]
No, Compile doesn't know the inputs or outputs of pack, that's Pack's job. For example, if someone deletes the nupkg but not the dll, Pack should still run. How does Compile know that Pack is out of date at that point?

Pack needs to tell MSBuild it's inputs and outputs, see: https://msdn.microsoft.com/en-us/library/ms171483.aspx.

**Pull request merged**
